framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(MAILER_FROM_EMAIL)%'
            recipients: ['%env(MAILER_TO_EMAIL)%']
        headers:
            From: 'Admin <%env(MAILER_FROM_EMAIL)%>'
